### ISSUE TITLE
有一些机型调不起分享,可以做一下兼容吗?

### ISSUE THREAD

**Issue by ziyexiao** [ahaSweather/MainUiFrame#1]
坚果pro2

**Comment by ahaSweather** [comment]
demo跑不起来吗？

**Comment by ziyexiao** [comment]
有一个手机可以打开demo运行,但是集成到我app就调不起来了,有一个手机demo都跑不动

**Comment by ahaSweather** [comment]
你是哪种方式调不起来？intent分享还是sdk分享，跑不动的那个手机上报的什么错

**Comment by ziyexiao** [comment]
发现问题了,跑不动demo的是阿里的小辣椒机型,好像不是安卓, 调不起来的是因为我固定是用QQ的appid,我再去调试一下,谢谢解答
